# 使用官方的 OpenJDK 镜像
FROM openjdk:17-jdk

# 设置工作目录
WORKDIR /app

# 复制构建好的 JAR 文件到容器
COPY target/*.jar app.jar

# 设置 Spring Boot 项目的启动命令
ENTRYPOINT ["java", "-jar", "/app/app.jar"]

# 映射容器端口到宿主机端口
EXPOSE 8082
